### ISSUE TITLE
Needs a better readme

### ISSUE THREAD

**Issue by riek-lt** [JacenBoy/Nuzlocke-Stream-Dashboard#2]
I am missing so much, for example: Where are the files to import in thte streaming layout? Or am I supposed to window-capture the program itself?

**Comment by JacenBoy** [comment]
Instructions were all placed in the wiki.
https://github.com/JacenBoy/Nuzlocke-Stream-Dashboard/wiki

**Comment by riek-lt** [comment]
Thanks. This should be in the readme however ;)
